"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    fork_in_the_road: 'When you come to a fork in the road, take it',
    observe_a_lot: 'You can observe a lot by just watching',
    it_aint_over: 'It ain’t over till it’s over',
    deja_vu: 'It’s like déjà vu all over again',
    too_crowded: 'No one goes there nowadays, it’s too crowded',
    baseball_is_mental: 'Baseball is 90% mental and the other half is physical',
    nickel_aint_a_dime: 'A nickel ain’t worth a dime anymore',
    goto_funerals: 'Always go to other people’s funerals, otherwise they won’t come to yours',
    too_many_mistakes: 'We made too many wrong mistakes',
    congratulations: 'Congratulations. I knew the record would stand until it was broken',
    im_not_hungry: 'You better cut the pizza in four pieces because I’m not hungry enough to eat six',
    weouldnt_have_won: 'You wouldn’t have won if we’d beaten you',
    two_hour_nap: 'I usually take a two-hour nap from one to four',
    anonymous_letter: 'Never answer an anonymous letter',
    no_slump: 'Slump? I ain’t in no slump… I just ain’t hitting',
    think_and_hit: 'How can you think and hit at the same time?',
    the_future: 'The future ain’t what it used to be',
    gets_late: 'It gets late early out here',
    people_at_the_ballpark: 'If the people don’t want to come out to the ballpark, nobody’s going to stop them',
    deep_depth: 'We have deep depth',
    pair_up: 'Pair up in threes',
    good_luggage: 'Why buy good luggage, you only use it when you travel',
    know_where_you_are_going: 'You’ve got to be very careful if you don’t know where you are going, because you might not get there',
    all_pitchers: 'All pitchers are liars or crybabies',
    napoleon_watergate: 'Even Napoleon had his Watergate',
    bill_dickey: 'Bill Dickey is learning me his experience',
    hes_amphibious: 'He hits from both sides of the plate. He’s amphibious',
    impossible_conversation: 'It was impossible to get a conversation going, everybody was talking too much',
    sandy_koufax: 'I can see how he won twenty-five games. What I don’t understand is how he lost five',
    encyclopedia: 'I’m not going to buy my kids an encyclopedia. Let them walk to school like I did',
    dont_know_nothing: 'In baseball, you don’t know nothing',
    never_said_things: 'I never said most of the things I said',
    it_aint_heat: 'It ain’t the heat, it’s the humility',
    ovewhelming_underdogs: 'We were overwhelming underdogs',
    towels_so_thick: 'The towels were so thick there I could hardly close my suitcase',
    parents_off_the_streets: 'Little League baseball is a very good thing because it keeps the parents off the streets',
    world_were_perfect: 'If the world were perfect, it wouldn’t be',
};
//# sourceMappingURL=quotes.js.map